// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ysacjkryavzgygnjpqja.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlzYWNqa3J5YXZ6Z3lnbmpwcWphIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEzNjQyMDMsImV4cCI6MjA2Njk0MDIwM30.tAvmp36HLIWOkAnZFlyYz7qtm8rqn59N1EN9eoBFp04";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});